# transitions.R -- the six Transition kinds (Transition.java). Every non-Terminal state needs
# exactly one of these. Unlike the other three layers, create_transition_settings()'s job
# includes restructuring `...` into the correctly-keyed output, since the JSON key itself
# (direct_transition / distributed_transition / ...) depends on `kind`, not a field inside a
# fixed-shape object -- the schema still drives field validation, assembly is just less uniform.

.transition_schema <- list(
  direct       = list(required = c("to"), optional = c()),
  distributed  = list(required = c("options"), optional = c(), array = c("options")),
  conditional  = list(required = c("options"), optional = c(), array = c("options")),
  complex      = list(required = c("options"), optional = c(), array = c("options")),
  lookup_table = list(required = c("lookup_table_name", "options"), optional = c(), array = c("options")),
  type_of_care = list(required = c("ambulatory", "telemedicine", "emergency"), optional = c())
)

#' Build a Transition settings object (Transition.java). Every non-Terminal state needs exactly
#' one of these.
#'
#' @param kind One of "direct", "distributed", "conditional", "complex", "lookup_table",
#'   "type_of_care". Purely an R-side selector -- Transition JSON has no discriminator field of
#'   its own; the key name itself (e.g. "direct_transition") is what discriminates.
#'
#' Every field used by any of the six kinds is a named argument here (all default NULL):
#'   - direct: `to` (a state name)
#'   - distributed: `options` = list of list(transition =, distribution =) (distribution is
#'     either a number, or list(attribute =, default =) for a NamedDistribution)
#'   - conditional: `options` = list of list(condition = <create_logic_settings() result, or
#'     omitted for the fallback/else branch>, transition =)
#'   - complex: `options` = list of list(condition = <optional>, transition = <xor> distributions
#'     = list of list(transition =, distribution =))
#'   - lookup_table: `lookup_table_name`, `options` = list of list(transition =,
#'     default_probability =) (the referenced CSV under generate.lookup_tables is the caller's
#'     responsibility -- not generated by this toolkit)
#'   - type_of_care: `ambulatory`, `telemedicine`, `emergency` (state names)
#' @param to,options,lookup_table_name,ambulatory,telemedicine,emergency See the kind-by-kind
#'   breakdown above; only the field(s) relevant to `kind` should be given.
#' @return A plain named list with exactly one `*_transition` key, ready to merge into a state.
#' @examples
#' create_transition_settings("direct", to = "Terminal")
#'
#' create_transition_settings("distributed", options = list(
#'   list(transition = "Recovers", distribution = 0.9),
#'   list(transition = "Death", distribution = 0.1)
#' ))
#' @export
create_transition_settings <- function(kind,
                                        to = NULL,
                                        options = NULL,
                                        lookup_table_name = NULL,
                                        ambulatory = NULL,
                                        telemedicine = NULL,
                                        emergency = NULL) {
  fields <- list(
    to = to,
    options = options,
    lookup_table_name = lookup_table_name,
    ambulatory = ambulatory,
    telemedicine = telemedicine,
    emergency = emergency
  )
  fields <- fields[!vapply(fields, is.null, logical(1))]

  entry <- .transition_schema[[kind]]
  if (is.null(entry)) {
    stop(sprintf("transition: unknown kind '%s'. Valid kinds: %s",
                 kind, paste(names(.transition_schema), collapse = ", ")))
  }
  .validate_settings(entry, fields, sprintf("transition '%s'", kind))
  fields <- .apply_array_rule(entry, fields)

  switch(kind,
    direct = list(direct_transition = fields$to),

    distributed = {
      opts <- lapply(fields$options, function(o) {
        if (is.null(o$transition)) stop("transition 'distributed': each option needs 'transition'")
        if (is.null(o$distribution)) stop("transition 'distributed': each option needs 'distribution'")
        list(transition = o$transition, distribution = o$distribution)
      })
      list(distributed_transition = unname(opts))
    },

    conditional = {
      opts <- lapply(fields$options, function(o) {
        if (is.null(o$transition)) stop("transition 'conditional': each option needs 'transition'")
        if (is.null(o$condition)) list(transition = o$transition)
        else list(condition = o$condition, transition = o$transition)
      })
      list(conditional_transition = unname(opts))
    },

    complex = {
      opts <- lapply(fields$options, function(o) {
        has_t <- !is.null(o$transition)
        has_d <- !is.null(o$distributions)
        if (has_t == has_d) {
          stop("transition 'complex': each option needs exactly one of 'transition' or 'distributions'")
        }
        item <- list()
        if (!is.null(o$condition)) item$condition <- o$condition
        if (has_t) item$transition <- o$transition else item$distributions <- unname(o$distributions)
        item
      })
      list(complex_transition = unname(opts))
    },

    lookup_table = {
      opts <- lapply(fields$options, function(o) {
        if (is.null(o$transition) || is.null(o$default_probability)) {
          stop("transition 'lookup_table': each option needs 'transition' and 'default_probability'")
        }
        list(transition = o$transition, lookup_table_name = fields$lookup_table_name,
             default_probability = o$default_probability)
      })
      list(lookup_table_transition = unname(opts))
    },

    type_of_care = list(type_of_care_transition = list(
      ambulatory = fields$ambulatory, telemedicine = fields$telemedicine, emergency = fields$emergency
    ))
  )
}
